	<table cellpadding="3" cellspacing="0">
		<tr><th>?</th><th>Color</th><th>Type</th></tr>
		<tr><td>-</td><td>White</td><td>None</td></tr>
		<tr><td>C</td><td>Cyan</td><td>Primary</td></tr>
		<tr><td>M</td><td>Magenta</td><td>Primary</td></tr>
		<tr><td>Y</td><td>Yellow</td><td>Primary</td></tr>
		<tr><td>R</td><td>Red</td><td>Secondary (M+Y)</td></tr>
		<tr><td>G</td><td>Green</td><td>Secondary (Y+C)</td></tr>
		<tr><td>B</td><td>Blue</td><td>Secondary (C+M)</td></tr>
		<tr><td>O</td><td>Orange</td><td>Tertiary (R+Y)</td></tr>
		<tr><td>A</td><td>Azure</td><td>Tertiary (B+C)</td></tr>
		<tr><td>V</td><td>Violet</td><td>Tertiary (B+M)</td></tr>
		<tr><td>K</td><td>Black</td><td>Tertiary (C+M+Y)</td></tr>
	</table>
